server:
  port: 8082
spring:
  application:
    name: orderservice
eureka:
  client:
    service-url:
      defaultZone: http://localhost:18080/eureka/

logging:
  level:
    root: info

#feign:
#  client:
#    config:
#      default:
#        loggerLevel: FULL

#feign:
#  httpclient:
#    enabled: true
#    max-connections: 200
#    max-connections-per-route: 50